# -*- coding: utf-8 -*-
"""Pretrained models in CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zwq6I_NUlS3Xw_iGMzhrUjqdIuXcfgdy
"""

# in this we give the image to the model then he show the result acording old models / Pretrained models

from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

model = ResNet50(weights='imagenet')

img_path = 'dog.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x=preprocess_input(x)

pres = model.predict(x)
print('Predicted:', decode_predictions(pres, top=3)[0])

img_path = 'mango.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x=preprocess_input(x)

pres = model.predict(x)
print('Predicted:', decode_predictions(pres, top=3)[0])

img_path = 'chair.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x=preprocess_input(x)

pres = model.predict(x)
print('Predicted:', decode_predictions(pres, top=3)[0])

